version: "3.8"
services:
    web:
        restart: unless-stopped
        container_name: uams-be
        image: 'ecoprohcm/uams-be:latest'
        ports:
            - '8079:8079'
networks:
    default:
        external: true
        name: dms-nw
