// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Mr. Khai"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/area": {
            "post": {
                "description": "Create area",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Area",
                "parameters": [
                    {
                        "description": "Fields need to create a area",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwagCreateArea"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Area"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete area using \"id\" field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Area By ID",
                "parameters": [
                    {
                        "description": "Area ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "type": "object"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update area, must have \"id\" field",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Area By ID",
                "parameters": [
                    {
                        "description": "Fields need to update a area",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwagUpdateArea"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/area/{id}": {
            "get": {
                "description": "find area info by area id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Area By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Area ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Area"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/areas": {
            "get": {
                "description": "find all areas info",
                "produces": [
                    "application/json"
                ],
                "summary": "Find All Area",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Area"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway": {
            "delete": {
                "description": "Delete gateway using \"id\" field. Send deleted info to MQTT broker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete Gateway By Gateway ID",
                "parameters": [
                    {
                        "description": "Gateway ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "type": "object"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "gateway_id": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update gateway, must have \"gateway_id\" field. Send updated info to MQTT broker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update Gateway By Gateway ID",
                "parameters": [
                    {
                        "description": "Fields need to update a gateway",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwagUpateGateway"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway/gateway_id/{gateway_id}": {
            "get": {
                "description": "find gateway and uhf info by gateway_id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Gateway By Gateway ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "gateway_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Gateway"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway/{id}": {
            "get": {
                "description": "find gateway and uhf info by id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Gateway By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Gateway"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway_logs": {
            "get": {
                "description": "find all gateway logs info",
                "produces": [
                    "application/json"
                ],
                "summary": "Find All GatewayLog",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.GatewayLog"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway_logs/gateway_id/{gateway_id}/period/{from}/{to}": {
            "get": {
                "description": "find Gateway logs by period of time",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Gateway logs by period of time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GatewayLog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Unix time",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To Unix time",
                        "name": "to",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.GatewayLog"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway_logs/gateway_id/{id}": {
            "get": {
                "description": "find gateway log info by Gateway id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find GatewayLog By Gateway ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GatewayLog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GatewayLog"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway_logs/period/{from}/{to}": {
            "get": {
                "description": "find Gateway logs by period of time",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Gateway logs by period of time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GatewayLog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Unix time",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To Unix time",
                        "name": "to",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.GatewayLog"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateway_logs/{id}": {
            "get": {
                "description": "find gateway log info by id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find GatewayLog By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GatewayLog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GatewayLog"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/gateways": {
            "get": {
                "description": "find all gateways info",
                "produces": [
                    "application/json"
                ],
                "summary": "Find All Gateway",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Gateway"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/operation_logs": {
            "get": {
                "description": "find all operation logs info",
                "produces": [
                    "application/json"
                ],
                "summary": "Find All OperationLog",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.OperationLog"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/operation_logs/gateway_id/{gateway_id}": {
            "get": {
                "description": "find operation log info by gateway_id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Operation By GatewayID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GatewayLog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OperationLog"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/operation_logs/gateway_id/{gateway_id}/period/{from}/{to}": {
            "get": {
                "description": "find operation logs by period of time",
                "produces": [
                    "application/json"
                ],
                "summary": "Find operation logs by period of time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Gateway ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Unix time",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To Unix time",
                        "name": "to",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OperationLog"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/operation_logs/period/{from}/{to}": {
            "get": {
                "description": "find Operation logs by period of time",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Operation logs by period of time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Gateway ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "From Unix time",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To Unix time",
                        "name": "to",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OperationLog"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/operation_logs/{id}": {
            "get": {
                "description": "find operation log info by id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Operation By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OperationLog"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses": {
            "get": {
                "description": "find all package access log",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/area_id/{area_id}": {
            "get": {
                "description": "find all package access log by  and AreaID",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by AreaID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/area_id/{area_id}/period/{from}/{to}": {
            "get": {
                "description": "find all package access log by AreaID and TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by AreaID and TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/package_id/{id}": {
            "get": {
                "description": "find all package access log by Package ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by Package ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/package_id/{id}/area_id/{area_id}": {
            "get": {
                "description": "find all package access log by Package ID and AreaID",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by Package ID and AreaID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/package_id/{id}/area_id/{area_id}/period/{from}/{to}": {
            "get": {
                "description": "find all package access log by Package ID and AreaID and TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by Package ID and AreaID and TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/package_id/{id}/period/{from}/{to}": {
            "get": {
                "description": "find all package access log by Package ID and TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by Package ID and TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/package_accesses/period/{from}/{to}": {
            "get": {
                "description": "find all package access log by TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find Package Access log by TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.PackageAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/uhf": {
            "delete": {
                "description": "Delete UHF using \"id\" field. Send deleted info to MQTT broker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete UHF By ID",
                "parameters": [
                    {
                        "description": "UHF Delete payload",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "type": "object"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update UHF, must have \"gatewayId\" and \"UHFAddress\" field. Send updated info to MQTT broker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update UHF By UHF Address and GatewayID",
                "parameters": [
                    {
                        "description": "Fields need to update a UHF",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UHF"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/uhf/{id}": {
            "get": {
                "description": "find UHF info by UHF id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find UHF By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UHF ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UHF"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/uhfs": {
            "get": {
                "description": "find all UHF info",
                "produces": [
                    "application/json"
                ],
                "summary": "Find All UHF",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UHF"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses": {
            "get": {
                "description": "find all user access log",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/area_id/{area_id}": {
            "get": {
                "description": "find all user access log by Area Id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by Area Id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/area_id/{area_id}/period/{from}/{to}": {
            "get": {
                "description": "find all user access log by Area Id and TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by Area Id and TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/period/{from}/{to}": {
            "get": {
                "description": "find all user access log by TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/user_id/{id}": {
            "get": {
                "description": "find all user access log by user id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by User ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/user_id/{id}/area_id/{area_id}": {
            "get": {
                "description": "find all user access log by user id and Area Id",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by User ID and Area Id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/user_id/{id}/area_id/{area_id}/period/{from}/{to}": {
            "get": {
                "description": "find all user access log by user id and Area Id and TimeRange",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by User ID and Area Id and TimeRange",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user_accesses/user_id/{id}/period/{from}/{to}": {
            "get": {
                "description": "find all user access log by user id and Time Range",
                "produces": [
                    "application/json"
                ],
                "summary": "Find User Access log by User ID and Time Range",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.UserAccess"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Area": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "manager": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Gateway": {
            "type": "object",
            "properties": {
                "area_id": {
                    "type": "string"
                },
                "connect_state": {
                    "type": "string"
                },
                "gateway_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "software_version": {
                    "type": "string"
                },
                "uhfs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UHF"
                    }
                }
            }
        },
        "models.GatewayLog": {
            "type": "object",
            "properties": {
                "gateway_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "log_time": {
                    "type": "string"
                },
                "state_type": {
                    "type": "string"
                },
                "state_value": {
                    "type": "string"
                }
            }
        },
        "models.OperationLog": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "corresponding statetype",
                    "type": "string"
                },
                "gateway_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.PackageAccess": {
            "type": "object",
            "properties": {
                "area_id": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "package_id": {
                    "type": "string"
                },
                "random": {
                    "type": "string"
                }
            }
        },
        "models.SwagCreateArea": {
            "type": "object",
            "properties": {
                "manager": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SwagUpateGateway": {
            "type": "object",
            "properties": {
                "areaId": {
                    "type": "string"
                },
                "gatewayId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SwagUpdateArea": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "manager": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UHF": {
            "type": "object",
            "properties": {
                "active_state": {
                    "type": "string"
                },
                "area_id": {
                    "type": "string"
                },
                "connect_state": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gateway_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "uhf_address": {
                    "type": "string"
                },
                "uhf_serial_number": {
                    "type": "string"
                }
            }
        },
        "models.UserAccess": {
            "type": "object",
            "properties": {
                "area_id": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "random": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "errorMsg": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://iot.hcmue.space:8079",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Backend API",
	Description:      "This is API document for UAMS backend server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
