name: CI/CD

on:
  pull_request:
    branches: [main]
    types: [opened, edited, closed]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Lint
        run: go fmt ./...

      - name: Swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.7.8
          swag --version
          make swagger

      - name: Deploy swagger
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.UAMS_HOST}}
          port: ${{secrets.UAMS_PORT}}
          username: sviot
          password: ${{secrets.UAMS_SSH_PASS}}
          source: "./docs/swagger.yaml"
          target: "$HOME/uams/swagger-ui"

  cd:
    needs: ci
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Build
        env:
          IMAGE_NAME: uams-be
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest ${{secrets.DOCKER_USER}}/$IMAGE_NAME:latest
          docker push ${{secrets.DOCKER_USER}}/$IMAGE_NAME

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: uams-be
        with:
          host: ${{secrets.UAMS_HOST}}
          port: ${{secrets.UAMS_PORT}}
          username: sviot
          password: ${{secrets.UAMS_SSH_PASS}}
          envs: IMAGE_NAME
          script: |
            docker login 
            docker pull ${{secrets.DOCKER_USER}}/$IMAGE_NAME
            cd $HOME/iot && docker-compose down && docker-compose up -d
